use_frameworks!

platform :ios, '8.0'

target 'AlipaySDK_No_UTDID_Example' do
  pod 'AlipaySDK_No_UTDID', :path => '../'

  target 'AlipaySDK_No_UTDID_Tests' do
    inherit! :search_paths

    
  end
end
