source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

use_frameworks!

platform :ios, '8.0'

target 'AlipaySDK_Dependency_UTDID_Example' do
  pod 'AlipaySDK_Dependency_UTDID', :path => '../'

  target 'AlipaySDK_Dependency_UTDID_Tests' do
    inherit! :search_paths

    
  end
end
